### ISSUE TITLE
Doesn't appear to work with more than one ruby version

### ISSUE THREAD

**Issue by stve** [collectiveidea/travis_bundle_cache#2]
I have my `.travis.yml` setup like so:

``` yaml
rvm:
- 1.9.3
- 2.0.0
```

Tests with 1.9.3 usually run first and use the bundle, followed by tests with 2.0.0. I can see in the output from `travis_bundle_install` that it's pulling down the archive, but then it proceeds to install the gems anyway.  The travis_bundle_log doesn't offer any clues:

```
Checking for changes
=> There were no changes, doing nothing
```

**Comment by albus522** [comment]
This is one of the things I need to work out. I am thinking of using the ruby version in the cache filename

**Comment by albus522** [comment]
And your next build should work right.

**Comment by stve** [comment]
That did the trick, thanks for the quick turnaround. I suspect there's probably still some issues around non-MRI rubies, but this worked for me. Cheers! :wine_glass:
