### ISSUE TITLE
Caching without S3: using a git repository

### ISSUE THREAD

**Issue by wvengen** [collectiveidea/travis_bundle_cache#3]
I'm not using S3 and am pondering the use of a git repository instead. This could even be on Github, using a separate repository with a deploy key.

Would this be a fruitful approach, or are there better storage solutions (that don't require additional services to signup for)?

**Comment by albus522** [comment]
Travis now handles caching natively for private repos: http://docs.travis-ci.com/user/caching/

**Comment by wvengen** [comment]
That's true, but many open source projects are still wasting cpu cycles - including mine.

**Comment by albus522** [comment]
Git would be quite complicated, but feel free to try.

**Comment by wvengen** [comment]
Thanks, I'll have a look at [wvengen/travis_bundle_cache](https://github.com/wvengen/travis_bundle_cache).

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
